import 'dart:ui';

const primaryColor = Color(0xFF092CF7);
const validationErrorColor = Color(0xFFFF0000);
const yellowColor = Color(0xFFFFDE00);
const successColor = Color(0xFF00BA88);
const background = Color(0xFFffffff);
const navigationBarBackground = primaryColor;
const statusBarWhiteBackground = Color(0x00FFFFFF);
const grayscale = Color(0xFFA0A3BD);
const offWhite = Color(0xFFFCFCFC);
const titleActive = Color(0xFF14142B);
const anchor = Color(0xFF1CC8EE);
const border = Color(0xFFD8D8D8);
const line = Color(0xFF092CF7);
const filled = Color(0xFFEDEDED);
const label = Color(0xFF6E7191);
const gray = Color(0xFF252422);
const greyLight = Color(0xFFD9D9D9);
const snackbarColor = Color(0xFFD1D1D1);
const dialogSuccessBackground = Color(0xFFE2FDF6);
const dialogSuccessBorder = Color(0xFF00BA88);
const dialogErrorBorder = Color(0xFFDD7A7A);
const dialogErrorBackground = Color(0xFFF7DFDF);
const dialogWarningBorder = Color(0xFFFFB93E);
const dialogWarningBackground = Color(0xFFFFF6E8);
const overlayColor = Color.fromARGB(125, 119, 119, 119);
