Map<String, String> mapNigeriaStates = {
  'Select': 'Select',
  "Abia": "Abia",
  "Adamawa": "Adamawa",
  "Akwa Ibom": "Akwa Ibom",
  "Anambra": "Anambra",
  "Bauchi": "Bauchi",
  "Bayelsa": "Bayelsa",
  "Benue": "Benue",
  "Borno": "Borno",
  "Cross River": "Cross River",
  "Delta": "Delta",
  "Ebonyi": "Ebonyi",
  "Edo": "Edo",
  "Ekiti": "Ekiti",
  "Enugu": "Enugu",
  "FCT - Abuja": "FCT - Abuja",
  "Gombe": "Gombe",
  "Imo": "Imo",
  "Jigawa": "Jigawa",
  "Kaduna": "Kaduna",
  "Kano": "Kano",
  "Katsina": "Katsina",
  "Kebbi": "Kebbi",
  "Kogi": "Kogi",
  "Kwara": "Kwara",
  "Lagos": "Lagos",
  "Nasarawa": "Nasarawa",
  "Niger": "Niger",
  "Ogun": "Ogun",
  "Ondo": "Ondo",
  "Osun": "Osun",
  "Oyo": "Oyo",
  "Plateau": "Plateau",
  "Rivers": "Rivers",
  "Sokoto": "Sokoto",
  "Taraba": "Taraba",
  "Yobe": "Yobe",
  "Zamfara": "Zamfara"
};

List<String> nigeriaStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara"
];
